# Magic Square

In dit document ga ik een Magische vierkant oplossen doormiddel van NumPy, een magische vierkant is een vierkante matrix waarvan alle cijfers die op een horizontale, verticale en diagonale lijn staan bij elkaar optellen naar hetzelfde getal.

Een voorbeeld van een Magische vierkant

\begin{bmatrix}
    8 & 3 & 4 \\
    1 & 5 & 9 \\
    6 & 7 & 2 \\
\end{bmatrix}

Dit vierkant telt in alle richtingen op tot het getal 15.

Het script wat wij gaan maken krijgt een matrix met een aantal getallen ingevuld en een aantal leeg, het script moet dan de missende getallen in de matrix zoeken.

## Oplossen van een Magic Square met NumPy

Eerst importeren wij NumPy

In [2]:
import numpy as np

Dit is ons Magische Vierkant wat wij gaan oplossen, de None betekent hier dat wij het getal niet kennen en deze dus moeten gaan uitrekenen.

In [3]:
magicSquare = np.array([
    8,     None,    None,
    None,  None,    7,
    None,  None,    2,
])

Dit zijn alle vergelijkingen uit het handmatig oplossen omgezet naar een matrix, de laatse rij is de 'R' rij, 'R' is het totaal van een rij, deze verwerken wij in de vergelijking, op deze manier word het totaal van alle rijen gelijk.

In [4]:
defaultComparisonArray = np.array([
    [1, 1, 1, 0, 0, 0, 0, 0, 0, -1],    # Horizontal 1
    [0, 0, 0, 1, 1, 1, 0, 0, 0, -1],    # Horizontal 2
    [0, 0, 0, 0, 0, 0, 1, 1, 1, -1],    # Horizontal 3
    [1, 0, 0, 1, 0, 0, 1, 0, 0, -1],    # Vertical 1
    [1, 0, 0, 0, 1, 0, 0, 0, 1, -1],    # Diagonally L -> R
    [0, 1, 0, 0, 1, 0, 0, 1, 0, -1],    # Vertical 2
    [0, 0, 1, 0, 1, 0, 1, 0, 0, -1],    # Diagonally R -> L
    [0, 0, 1, 0, 0, 1, 0, 0, 1, -1],    # Vertical 3
    [0, 0, 0, 0, 3, 0, 0, 0, 0, -1],    # Total of each row
])

In [5]:
comparisonMagicSquare = np.zeros(shape=(9, 1))

Een aantal getallen die in de vergelijking staan kennen wij al, deze gaan wij nu weghalen uit de vergelijking en aftrekken van de ...

In [6]:
for rowKey in range(len(defaultComparisonArray) - 1):
    for numberKey in range(len(defaultComparisonArray[rowKey]) - 1):

        # Als wij de waarde niet kennen gaan wij door
        if magicSquare[numberKey] is None:
            continue

        comparisonMagicSquare[rowKey] -= defaultComparisonArray[rowKey][numberKey] * magicSquare[numberKey]
        defaultComparisonArray[rowKey][numberKey] = 0

Omdat de dimensies niet kloppen en wij dus niet kunnen vermenigvuldigen gaan wij de (pseudo) inverse van de matrix berekenen, omdat deze wel de correcte dimensies heeft.

In [7]:
inverseComparisonArray = np.linalg.pinv(defaultComparisonArray)

Dit is de belangerijkste stap, wij gaan nu de inverse van de vergelijkingen matrix nemen en deze vermenigvuldigen met de 'comparisonMagicSquare'

In [ ]:
solutionVector = inverseComparisonArray.dot(comparisonMagicSquare)

Nu wij de antwoorden hebben berekent gaan wij de getallen die wij vooraf niet wisten invullen.

In [8]:
for item in range(len(magicSquare) - 1):
    if magicSquare[item] is None:
        magicSquare[item] = solutionVector[item][0]

Nu wij de antwoorden hebben hoeven wij ze alleen nog maar leesbaar te maken, hier zetten wij de vector om naar een matrix omdat dat logischer is voor een persoon.

In [9]:
finalSolution = np.around(magicSquare.astype(np.double), 3)
finalSolution.resize(3, 3)

In [11]:
print(finalSolution)

[[8. 1. 6.]
 [3. 5. 7.]
 [4. 9. 2.]]
