# Magic Square

In dit document ga ik een Magische vierkant oplossen doormiddel van NumPy, een magische vierkant is een vierkante matrix waarvan alle cijfers die op een horizontale, verticale en diagonale lijn staan bij elkaar optellen naar hetzelfde getal.

Een voorbeeld van een Magische vierkant

\begin{bmatrix}
    8 & 3 & 4 \\
    1 & 5 & 9 \\
    6 & 7 & 2 \\
\end{bmatrix}

Dit vierkant telt in alle richtingen op tot het getal 15.

Om dit op te kunnen lossen moeten wij dit probleem zien als een stelsel vergelijking in de matrix vorm.

$A \vec{x} = \vec{b}$

## Oplossen van een Magic Square

Dit is ons Magische Vierkant wat wij gaan oplossen.

\begin{bmatrix}
    8 & ? & ? \\
    ? & ? & 7 \\
    ? & ? & 2 \\
\end{bmatrix}

Dit is hoe het in de code er uit ziet.

In [2]:
import numpy as np

magicSquare = np.array([
    8,     None,    None,
    None,  None,    7,
    None,  None,    2,
])

Om dit magische vierkant op te kunnen lossen moeten wij de vergelijkingen opstellen die er voor gaan zorgen dat alle rijen, columen en diagonalen dezelfde sum krijgen. Deze sum noemen wij $r$.

Ook is er 1 andere vergelijking, dat is de totaal vergelijking. Bij een magische vierkant is het middelste getal (bij ons dus $A_{5}$) x 3 altijd gelijk aan $r$.

**Horizontaal**

$
A_{1} \cdot 1 + A_{2} \cdot 1 + A_{3} \cdot 1 - r = 0 \\
A_{4} \cdot 1 + A_{5} \cdot 1 + A_{6} \cdot 1 - r = 0 \\
A_{7} \cdot 1 + A_{8} \cdot 1 + A_{0} \cdot 1 - r = 0 \\ 
$

**Verticaal**

$
A_{1} \cdot 1 + A_{4} \cdot 1 + A_{7} \cdot 1 - r = 0 \\
A_{2} \cdot 1 + A_{5} \cdot 1 + A_{8} \cdot 1 - r = 0  \\
A_{3} \cdot 1 + A_{6} \cdot 1 + A_{9} \cdot 1 - r = 0 \\ 
$

**Diagnonaal**

$
A_{1} \cdot 1 + A_{3} \cdot 1 + A_{9} \cdot 1 - r = 0 \\
A_{3} \cdot 1 + A_{5} \cdot 1 + A_{7} \cdot 1 - r = 0  \\
$

**Totaal**

$
A_{5} \cdot 3 - r = 0
$

Dit zetten wij om naar een Matrix.

\begin{bmatrix}
    1 &  1 &  1 &  0 &  0 &  0 &  0 &  0 &  0 &  -1 \\
    0 &  0 &  0 &  1 &  1 &  1 &  0 &  0 &  0 &  -1 \\
    0 &  0 &  0 &  0 &  0 &  0 &  1 &  1 &  1 &  -1 \\
    1 &  0 &  0 &  1 &  0 &  0 &  1 &  0 &  0 &  -1 \\
    0 &  1 &  0 &  0 &  1 &  0 &  0 &  1 &  0 &  -1 \\
    0 &  0 &  1 &  0 &  0 &  1 &  0 &  0 &  1 &  -1 \\
    1 &  0 &  0 &  0 &  1 &  0 &  0 &  0 &  1 &  -1 \\
    0 &  0 &  1 &  0 &  1 &  0 &  1 &  0 &  0 &  -1 \\
    0 &  0 &  0 &  0 &  3 &  0 &  0 &  0 &  0 &  -1 \\
\end{bmatrix}

Dit is hoe het er uit ziet in code

In [3]:
defaultComparisonArray = np.array([
    [1, 1, 1, 0, 0, 0, 0, 0, 0, -1],    # Horizontal 1
    [0, 0, 0, 1, 1, 1, 0, 0, 0, -1],    # Horizontal 2
    [0, 0, 0, 0, 0, 0, 1, 1, 1, -1],    # Horizontal 3
    [1, 0, 0, 1, 0, 0, 1, 0, 0, -1],    # Vertical 1
    [1, 0, 0, 0, 1, 0, 0, 0, 1, -1],    # Diagonally L -> R
    [0, 1, 0, 0, 1, 0, 0, 1, 0, -1],    # Vertical 2
    [0, 0, 1, 0, 1, 0, 1, 0, 0, -1],    # Diagonally R -> L
    [0, 0, 1, 0, 0, 1, 0, 0, 1, -1],    # Vertical 3
    [0, 0, 0, 0, 3, 0, 0, 0, 0, -1],    # Total of each row
])

In [4]:
comparisonMagicSquare = np.zeros(shape=(9, 1))

Voor het nemen van de inverse van de matrix moet de matrix vierkant zijn, op dit moment is de matrix 10x9, wij kunnen hier een 9x9 van maken door de getallen die wij kennen al weg te halen uit de vergelijking. 

Zo ziet dit er uit in de code.

In [5]:
for rowKey in range(len(defaultComparisonArray) - 1):
    for numberKey in range(len(defaultComparisonArray[rowKey]) - 1):

        # Als wij de waarde niet kennen gaan wij door
        if magicSquare[numberKey] is None:
            continue

        comparisonMagicSquare[rowKey] -= defaultComparisonArray[rowKey][numberKey] * magicSquare[numberKey]
        defaultComparisonArray[rowKey][numberKey] = 0

Omdat de determinant van de matrix 0 is, bestaat er geen inverse van de matrix. Wij kunnen wel een schatting van de inverse nemen. Dit heet een pseudo inverse. Wij kunnen dit doen door een functie uit NumPy te gebruiken.

Dit ziet er uit als volgt.

In [11]:
inverseComparisonArray = np.linalg.pinv(defaultComparisonArray)

Wij kunnen nu de missende getallen uitrekenen door het dot product te nemen.

Omdat wij de vergelijkingen hebben aangepast om deze vierkant te maken staan er nu op de plekken waarvan wij de getallen al wisten 'incorrecte' getallen (niet echt incorrect natuurlijk, maar incorrect omdat dit niet het antwoord is voor het magische vierkant)

In [13]:
solutionVector = inverseComparisonArray.dot(comparisonMagicSquare)

Wij hebben nu de antwoorden, deze hoeven wij nu alleen nog maar in te vullen op de plekken waar de getallen miste.

In [8]:
for item in range(len(magicSquare) - 1):
    if magicSquare[item] is None:
        magicSquare[item] = solutionVector[item][0]

En wij maken ze wat beter leesbaar.

In [9]:
finalSolution = np.around(magicSquare.astype(np.double), 3)
finalSolution.resize(3, 3)

In [10]:
print(finalSolution)

[[8. 1. 6.]
 [3. 5. 7.]
 [4. 9. 2.]]
